apiVersion: v1
kind: Namespace
metadata:
  name: newstalk-ai
  labels:
    app: newstalk-ai
    environment: production
    version: "1.0.0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: newstalk-ai-quota
  namespace: newstalk-ai
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: newstalk-ai-limits
  namespace: newstalk-ai
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim 