apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: newstalk-ai
  labels:
    app: newstalk-ai
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newstalk-ai
      component: redis
  template:
    metadata:
      labels:
        app: newstalk-ai
        component: redis
    spec:
      containers:
      - name: redis
        image: redis/redis-stack:7.2.0-v7
        ports:
        - containerPort: 6379
        - containerPort: 8001
        args:
        - redis-server
        - /etc/redis/redis.conf
        - --maxmemory
        - 512mb
        - --maxmemory-policy
        - allkeys-lru
        - --appendonly
        - "yes"
        - --appendfsync
        - everysec
        env:
        - name: REDIS_ARGS
          value: "--appendonly yes --appendfsync everysec"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "768Mi"
            cpu: "500m"
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc
      - name: redis-config
        configMap:
          name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: newstalk-ai
  labels:
    app: newstalk-ai
    component: redis
spec:
  selector:
    app: newstalk-ai
    component: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  - name: redis-insight
    port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: newstalk-ai
  labels:
    app: newstalk-ai
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: newstalk-ai
  labels:
    app: newstalk-ai
    component: redis
data:
  redis.conf: |
    # Redis configuration for NewsTalk AI
    bind 0.0.0.0
    port 6379
    
    # Memory management
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    appendonly yes
    appendfsync everysec
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    
    # Security
    protected-mode no
    
    # Performance
    tcp-keepalive 300
    timeout 0
    
    # Logging
    loglevel notice
    
    # TimeSeries module configuration
    loadmodule /opt/redis-stack/lib/redistimeseries.so 